/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountProfileCard: typeof import('./src/components/user/AccountProfileCard.vue')['default']
    AdminUsersTable: typeof import('./src/components/admin/AdminUsersTable.vue')['default']
    AuthShell: typeof import('./src/components/auth/AuthShell.vue')['default']
    CaptchaDialog: typeof import('./src/components/auth/CaptchaDialog.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    InDevCard: typeof import('./src/components/InDevCard.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NCode: typeof import('naive-ui')['NCode']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NH1: typeof import('naive-ui')['NH1']
    NH2: typeof import('naive-ui')['NH2']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NMenu: typeof import('naive-ui')['NMenu']
    NModal: typeof import('naive-ui')['NModal']
    NPagination: typeof import('naive-ui')['NPagination']
    NResult: typeof import('naive-ui')['NResult']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NStatistic: typeof import('naive-ui')['NStatistic']
    NStep: typeof import('naive-ui')['NStep']
    NSteps: typeof import('naive-ui')['NSteps']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    Provider: typeof import('./src/components/Provider.vue')['default']
    RoleEditorDialog: typeof import('./src/components/admin/RoleEditorDialog.vue')['default']
    RoleTag: typeof import('./src/components/workspace/RoleTag.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollableTableRegion: typeof import('./src/components/workspace/ScrollableTableRegion.vue')['default']
    UserActionDialogs: typeof import('./src/components/admin/UserActionDialogs.vue')['default']
    WorkspacePage: typeof import('./src/components/workspace/WorkspacePage.vue')['default']
    YggdrasilStatusCard: typeof import('./src/components/user/YggdrasilStatusCard.vue')['default']
  }
}
