// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/lyimoexiao/akari/internal/auth"
	"github.com/lyimoexiao/akari/internal/authadapter"
	"github.com/lyimoexiao/akari/internal/closet"
	"github.com/lyimoexiao/akari/internal/closetadapter"
	"github.com/lyimoexiao/akari/internal/config"
	"github.com/lyimoexiao/akari/internal/database"
	"github.com/lyimoexiao/akari/internal/permission"
	"github.com/lyimoexiao/akari/internal/rbacadapter"
	"github.com/lyimoexiao/akari/internal/requestlog"
	"github.com/lyimoexiao/akari/internal/requestlogadapter"
	"github.com/lyimoexiao/akari/internal/role"
	"github.com/lyimoexiao/akari/internal/router"
	"github.com/lyimoexiao/akari/internal/routeradapter"
	"github.com/lyimoexiao/akari/internal/score"
	"github.com/lyimoexiao/akari/internal/scoreadapter"
	"github.com/lyimoexiao/akari/internal/sign"
	"github.com/lyimoexiao/akari/internal/signadapter"
	"github.com/lyimoexiao/akari/internal/skinlib"
	"github.com/lyimoexiao/akari/internal/textureadapter"
	"github.com/lyimoexiao/akari/internal/user"
	"github.com/lyimoexiao/akari/internal/useradapter"
	"github.com/lyimoexiao/akari/internal/yggdrasil"
	"github.com/lyimoexiao/akari/internal/yggdrasiladapter"
	"github.com/lyimoexiao/akari/pkg/cache"
	"github.com/lyimoexiao/akari/pkg/captcha"
	"github.com/lyimoexiao/akari/pkg/jwt"
	"github.com/lyimoexiao/akari/pkg/logger"
	"github.com/lyimoexiao/akari/pkg/response"
	"github.com/lyimoexiao/akari/pkg/smtp"
	"github.com/lyimoexiao/akari/pkg/util"
	"github.com/lyimoexiao/akari/pkg/version"
	"go.uber.org/zap"
	"gorm.io/gorm"
	"path/filepath"
	"strings"
	"time"
)

// Injectors from wire.go:

func Initialize(cfgPath string) (*App, func(), error) {
	config, err := ProvideConfig(cfgPath)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := ProvideDB(config)
	if err != nil {
		return nil, nil, err
	}
	cache, cleanup2, err := ProvideCache(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	healthChecker := ProvideHealthChecker(db, cache)
	repository := ProvideRequestLogRepository(db)
	sugaredLogger, cleanup3, err := ProvideLogger(config)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	handlerFunc := ProvideRequestLogMiddleware(repository, sugaredLogger)
	service := ProvideCaptcha(config, cache)
	manager := ProvideJWTManager(config)
	mailer, cleanup4, err := ProvideMailer(config, sugaredLogger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	rbacadapterManager, err := ProvideRBACManager(db)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	roleService := ProvideRoleService(rbacadapterManager)
	authService := ProvideAuthService(db, cache, manager, mailer, config, roleService, sugaredLogger)
	middleware := ProvideAuthMiddleware(authService)
	handler := ProvideAuthHandler(authService, middleware, config, service, sugaredLogger)
	userService := ProvideUserService(db)
	permissionService := ProvidePermissionService(rbacadapterManager)
	permissionMiddleware := ProvidePermissionMiddleware(permissionService)
	userHandler := ProvideUserHandler(userService, permissionMiddleware, sugaredLogger)
	roleHandler := ProvideRoleHandler(roleService, permissionMiddleware, sugaredLogger)
	permissionHandler := ProvidePermissionHandler(permissionService, permissionMiddleware, sugaredLogger)
	requestlogService := ProvideRequestLogService(repository)
	requestlogHandler := ProvideRequestLogHandler(requestlogService, sugaredLogger)
	keyManager, err := ProvideYggdrasilKeyManager()
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	yggdrasilService := ProvideYggdrasilService(db, cache, config, sugaredLogger, keyManager)
	yggdrasilHandler := ProvideYggdrasilHandler(yggdrasilService, sugaredLogger)
	signadapterRepository := ProvideSignRepository(db)
	scoreadapterRepository := ProvideScoreOperator(db)
	signService := ProvideSignService(config, signadapterRepository, scoreadapterRepository)
	signHandler := ProvideSignHandler(signService, sugaredLogger)
	scoreHandler := ProvideScoreHandler(scoreadapterRepository, permissionMiddleware, sugaredLogger)
	fileStorage := ProvideTextureFileStorage(config)
	skinlibService := ProvideSkinlibService(db, fileStorage, scoreadapterRepository, config)
	skinlibHandler := ProvideSkinlibHandler(skinlibService, permissionMiddleware, sugaredLogger)
	textureChecker := ProvideTextureChecker(db)
	closetService := ProvideClosetService(db, textureChecker, scoreadapterRepository, config)
	closetHandler := ProvideClosetHandler(closetService, permissionMiddleware, sugaredLogger)
	handlers := &router.Handlers{
		Auth:       handler,
		User:       userHandler,
		Role:       roleHandler,
		Permission: permissionHandler,
		RequestLog: requestlogHandler,
		Yggdrasil:  yggdrasilHandler,
		Sign:       signHandler,
		Score:      scoreHandler,
		Skinlib:    skinlibHandler,
		Closet:     closetHandler,
	}
	textureFileHandler := ProvideTextureServer(config)
	dependencies := &router.Dependencies{
		Health:         healthChecker,
		RequestLogging: handlerFunc,
		Captcha:        service,
		Handlers:       handlers,
		Auth:           middleware,
		Logger:         sugaredLogger,
		TextureServer:  textureFileHandler,
	}
	engine := ProvideEngine(config, dependencies)
	app := &App{
		Config:     config,
		Engine:     engine,
		Logger:     sugaredLogger,
		Mailer:     mailer,
		CaptchaSvc: service,
	}
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type App struct {
	Engine     *gin.Engine
	Logger     *zap.SugaredLogger
	Config     *config.Config
	Mailer     *smtp.Mailer
	CaptchaSvc *captcha.Service
}

func ProvideConfig(cfgPath string) (*config.Config, error) {
	return config.Load(cfgPath)
}

func ProvideLogger(cfg *config.Config) (*zap.SugaredLogger, func(), error) {
	logger.Init(&cfg.Logger)
	cleanup := func() {
		_ = logger.L.Sync()
	}
	return logger.L, cleanup, nil
}

func ProvideDB(cfg *config.Config) (*gorm.DB, func(), error) {
	db, err := database.New(&cfg.Database)
	if err != nil {
		return nil, nil, err
	}
	if err := yggdrasiladapter.Migrate(db); err != nil {
		_ = database.Close(db)
		return nil, nil, err
	}
	cleanup := func() {
		_ = database.Close(db)
	}
	return db, cleanup, nil
}

func ProvideCache(cfg *config.Config) (cache.Cache, func(), error) {
	c := cache.New(&cfg.Cache)
	cleanup := func() {
		_ = c.Close()
	}
	return c, cleanup, nil
}

func ProvideMailer(cfg *config.Config, logger2 *zap.SugaredLogger) (*smtp.Mailer, func(), error) {
	m := smtp.New(&cfg.SMTP, logger2)
	cleanup := func() {
		_ = m.Close()
	}
	return m, cleanup, nil
}

func ProvideEngine(
	cfg *config.Config,
	deps *router.Dependencies,
) *gin.Engine {
	setGinMode(cfg.Server.Mode)
	return router.Setup(deps)
}

func ProvideCaptcha(cfg *config.Config, c cache.Cache) *captcha.Service {
	return captcha.New(&cfg.Captcha, c)
}

func ProvideJWTManager(cfg *config.Config) *jwt.Manager {
	exp, _ := time.ParseDuration(cfg.JWT.Expiration)
	return jwt.New(&jwt.Config{
		Secret:     cfg.JWT.Secret,
		Issuer:     cfg.JWT.Issuer,
		Expiration: exp,
	})
}

func ProvideAuthService(
	db *gorm.DB,
	c cache.Cache,
	jwtManager *jwt.Manager,
	mailer *smtp.Mailer,
	cfg *config.Config,
	roles *role.Service, logger2 *zap.SugaredLogger,
) *auth.Service {
	return auth.NewService(auth.Dependencies{
		Users:  authadapter.NewUserRepository(db),
		Roles:  roles,
		Tokens: authadapter.NewJWTManager(jwtManager),
		Store:  authadapter.NewTokenStore(c, logger2),
		Mailer: mailer,
		Settings: auth.Settings{
			RegistrationEnabled:      cfg.Auth.RegistrationEnabled,
			EmailVerificationEnabled: cfg.Auth.EmailVerificationEnabled,
			PasswordResetEnabled:     cfg.Auth.PasswordResetEnabled,
			VerifyEmailTokenTTL:      util.ParseDuration(cfg.Auth.VerifyEmailTokenTTL, 2*time.Hour),
			PasswordResetTokenTTL:    util.ParseDuration(cfg.Auth.PasswordResetTokenTTL, 30*time.Minute),
		},
	})
}

func ProvideAuthHandler(
	svc *auth.Service,
	mw *auth.Middleware,
	cfg *config.Config,
	captchaSvc *captcha.Service, logger2 *zap.SugaredLogger,
) *auth.Handler {
	return auth.NewHandler(svc, mw, &auth.HandlerConfig{
		RegistrationEnabled:      cfg.Auth.RegistrationEnabled,
		EmailVerificationEnabled: cfg.Auth.EmailVerificationEnabled,
	}, captchaSvc, logger2)
}

func ProvideAuthMiddleware(svc *auth.Service) *auth.Middleware {
	return auth.NewMiddleware(svc)
}

func ProvideRBACManager(db *gorm.DB) (*rbacadapter.Manager, error) {
	return rbacadapter.NewManager(db)
}

func ProvidePermissionService(manager *rbacadapter.Manager) *permission.Service {
	return permission.NewService(manager)
}

func ProvidePermissionMiddleware(svc *permission.Service) *permission.Middleware {
	return permission.NewMiddleware(svc)
}

func ProvidePermissionHandler(svc *permission.Service, middleware *permission.Middleware, logger2 *zap.SugaredLogger) *permission.Handler {
	return permission.NewHandler(svc, middleware, logger2)
}

func ProvideRequestLogRepository(db *gorm.DB) *requestlogadapter.Repository {
	return requestlogadapter.NewRepository(db)
}

func ProvideRequestLogService(repository *requestlogadapter.Repository) *requestlog.Service {
	return requestlog.NewService(repository)
}

func ProvideRequestLogMiddleware(repository *requestlogadapter.Repository, logger2 *zap.SugaredLogger) gin.HandlerFunc {
	return requestlog.Middleware(repository, logger2)
}

func ProvideRequestLogHandler(svc *requestlog.Service, logger2 *zap.SugaredLogger) *requestlog.Handler {
	return requestlog.NewHandler(svc, logger2)
}

func ProvideUserService(db *gorm.DB) *user.Service {
	return user.NewService(user.Dependencies{
		Repository: useradapter.NewRepository(db),
		Clock:      useradapter.Clock{},
		Hasher:     useradapter.PasswordHasher{},
	})
}

func ProvideUserHandler(svc *user.Service, permissions *permission.Middleware, logger2 *zap.SugaredLogger) *user.Handler {
	return user.NewHandler(svc, permissions, logger2)
}

func ProvideRoleService(manager *rbacadapter.Manager) *role.Service {
	return role.NewService(role.Dependencies{Repository: manager, Policies: manager})
}

func ProvideRoleHandler(svc *role.Service, permissions *permission.Middleware, logger2 *zap.SugaredLogger) *role.Handler {
	return role.NewHandler(svc, permissions, logger2)
}

func ProvideScoreOperator(db *gorm.DB) *scoreadapter.Repository {
	return scoreadapter.NewRepository(db)
}

func ProvideSignRepository(db *gorm.DB) *signadapter.Repository {
	return signadapter.NewRepository(db)
}

func ProvideSignService(cfg *config.Config, repo *signadapter.Repository, ops *scoreadapter.Repository) *sign.Service {
	return sign.NewService(sign.Dependencies{
		Repository: repo,
		ScoreOps:   ops,
		Config: sign.SignConfig{
			GapHours:  cfg.Score.SignGapHours,
			ScoreMin:  cfg.Score.SignScoreMin,
			ScoreMax:  cfg.Score.SignScoreMax,
			AfterZero: cfg.Score.SignAfterZero,
		},
		Clock: signadapter.Clock{},
	})
}

func ProvideSignHandler(svc *sign.Service, logger2 *zap.SugaredLogger) *sign.Handler {
	return sign.NewHandler(svc, logger2)
}

func ProvideScoreHandler(ops *scoreadapter.Repository, permissions *permission.Middleware, logger2 *zap.SugaredLogger) *score.Handler {
	return score.NewHandler(ops, permissions, logger2)
}

func ProvideHealthChecker(db *gorm.DB, cacheBackend cache.Cache) router.HealthChecker {
	return routeradapter.NewHealthChecker(db, cacheBackend)
}

func ProvideYggdrasilKeyManager() (*yggdrasiladapter.KeyManager, error) {

	return yggdrasiladapter.NewKeyManager("data")
}

func ProvideYggdrasilService(db *gorm.DB, c cache.Cache, cfg *config.Config, logger2 *zap.SugaredLogger, km *yggdrasiladapter.KeyManager) *yggdrasil.Service {
	return yggdrasil.NewService(yggdrasil.Dependencies{
		Repository: yggdrasiladapter.NewRepository(db),
		Sessions:   yggdrasiladapter.NewSessionStore(c),
		Signer:     km,
		Reporter:   yggdrasiladapter.NewSigningFailureReporter(logger2),
		Settings: yggdrasil.Settings{
			EmailVerificationEnabled: cfg.Auth.EmailVerificationEnabled,
			ServerName:               cfg.Yggdrasil.ServerName,
			ImplementationName:       cfg.Yggdrasil.ImplementationName,
			Description:              cfg.Yggdrasil.Description,
			ImplementationVersion:    version.Version,
			TextureBaseURL:           cfg.Server.BaseURL,
		},
	})
}

func ProvideYggdrasilHandler(svc *yggdrasil.Service, logger2 *zap.SugaredLogger) *yggdrasil.Handler {
	return yggdrasil.NewHandler(svc, logger2)
}

func ProvideTextureFileStorage(cfg *config.Config) *textureadapter.FileStorage {
	return textureadapter.NewFileStorage(cfg.Storage.Dir)
}

func ProvideTextureChecker(db *gorm.DB) *textureadapter.TextureChecker {
	return textureadapter.NewTextureChecker(db)
}

func ProvideSkinlibService(
	db *gorm.DB,
	storage *textureadapter.FileStorage,
	scoreOps *scoreadapter.Repository,
	cfg *config.Config,
) *skinlib.Service {
	return skinlib.NewService(skinlib.Dependencies{
		Repository:    textureadapter.NewRepository(db),
		Storage:       storage,
		ScoreOps:      scoreOps,
		ClosetAdder:   closetadapter.NewRepository(db),
		ClosetCleaner: closetadapter.NewRepository(db),
		BaseURL:       cfg.Server.BaseURL,
		AwardUpload:   cfg.Score.AwardPerUpload,
	})
}

func ProvideSkinlibHandler(svc *skinlib.Service, permissions *permission.Middleware, logger2 *zap.SugaredLogger) *skinlib.Handler {
	return skinlib.NewHandler(svc, permissions, logger2)
}

func ProvideClosetService(
	db *gorm.DB,
	textureChecker *textureadapter.TextureChecker,
	scoreOps *scoreadapter.Repository,
	cfg *config.Config,
) *closet.Service {
	return closet.NewService(closet.Dependencies{
		Repository:          closetadapter.NewRepository(db),
		TextureRepo:         textureChecker,
		TextureDeleter:      textureChecker,
		ProfileCleaner:      yggdrasiladapter.NewRepository(db),
		ScoreOps:            scoreOps,
		CostPerItem:         cfg.Score.CostPerClosetItem,
		ReturnScoreOnRemove: cfg.Score.ReturnScoreOnRemove,
		AwardPerLike:        cfg.Score.AwardPerLike,
	})
}

func ProvideClosetHandler(svc *closet.Service, permissions *permission.Middleware, logger2 *zap.SugaredLogger) *closet.Handler {
	return closet.NewHandler(svc, permissions, logger2)
}

func ProvideTextureServer(cfg *config.Config) router.TextureFileHandler {
	dir := cfg.Storage.Dir
	return func(ctx *gin.Context) {
		hash := ctx.Param("hash")
		if hash == "" {
			response.BadRequest(ctx, "缺少 hash 参数")
			return
		}
		if len(hash) < 2 {
			response.BadRequest(ctx, "无效的 hash")
			return
		}

		filePath := filepath.Join(dir, hash[:2], hash)

		ctx.Header("Content-Type", "image/png")

		ctx.Header("Access-Control-Allow-Origin", "*")
		ctx.File(filePath)
	}
}

func setGinMode(mode string) {
	switch strings.ToLower(mode) {
	case "release", "prod", "production":
		gin.SetMode(gin.ReleaseMode)
	case "test":
		gin.SetMode(gin.TestMode)
	default:
		gin.SetMode(gin.DebugMode)
	}
}
