// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/lyimoexiao/akari/internal/cache"
	"github.com/lyimoexiao/akari/internal/config"
	"github.com/lyimoexiao/akari/internal/database"
	"github.com/lyimoexiao/akari/internal/logger"
	"github.com/lyimoexiao/akari/internal/router"
	"go.uber.org/zap"
	"gorm.io/gorm"
	"strings"
)

// Injectors from wire.go:

func Initialize(cfgPath string) (*App, func(), error) {
	config, err := ProvideConfig(cfgPath)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := ProvideDB(config)
	if err != nil {
		return nil, nil, err
	}
	cache, cleanup2, err := ProvideCache(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	engine := ProvideEngine(config, db, cache)
	sugaredLogger, cleanup3, err := ProvideLogger(config)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app := &App{
		Config: config,
		Engine: engine,
		Logger: sugaredLogger,
	}
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type App struct {
	Engine *gin.Engine
	Logger *zap.SugaredLogger
	Config *config.Config
}

func ProvideConfig(cfgPath string) (*config.Config, error) {
	return config.Load(cfgPath)
}

func ProvideLogger(cfg *config.Config) (*zap.SugaredLogger, func(), error) {
	logger.Init(&cfg.Logger)
	cleanup := func() {
		_ = logger.L.Sync()
	}
	return logger.L, cleanup, nil
}

func ProvideDB(cfg *config.Config) (*gorm.DB, func(), error) {
	db, err := database.New(&cfg.Database)
	if err != nil {
		return nil, nil, err
	}
	cleanup := func() {
		_ = database.Close(db)
	}
	return db, cleanup, nil
}

func ProvideCache(cfg *config.Config) (cache.Cache, func(), error) {
	c := cache.New(&cfg.Cache)
	cleanup := func() {
		_ = c.Close()
	}
	return c, cleanup, nil
}

func ProvideEngine(cfg *config.Config, db *gorm.DB, c cache.Cache) *gin.Engine {
	setGinMode(cfg.Server.Mode)
	return router.Setup(db, c)
}

func setGinMode(mode string) {
	switch strings.ToLower(mode) {
	case "release", "prod", "production":
		gin.SetMode(gin.ReleaseMode)
	case "test":
		gin.SetMode(gin.TestMode)
	default:
		gin.SetMode(gin.DebugMode)
	}
}
